output "instance_private_ip_addr" {
  description = "Instance private IP"
  value       = aws_instance.web.private_ip
}

output "instance_public_ip_addr" {
  description = "Instance public IP"
  value       = aws_instance.web.public_ip
}

output "ssh_key" {
  description = "ssh key generated by terraform"
  sensitive   = true
  value       = tls_private_key.tls_key.private_key_pem
}
